import type { Metadata } from "next";
import { Lato } from "next/font/google";
import '../app/globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
    weight: [ "100", "300", "400", "700", "900"],
    style: ["normal", "italic"],
    subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`p-12 ${lato.className}`}
      >
        {children}
      </body>
    </html>
  );
}
